#!/usr/bin/python3
import sys

def factorization():
    try:
        filename = sys.argv[1]
        with open(filename) as file:
            for line in file:
                number = int(line)
                if number % 2 == 0:
                    print("{}={}*{}".format(number, number // 2, 2))
                    continue
                divisor = 3
                while divisor < number // 2:
                    if number % divisor == 0:
                        print("{}={}*{}".format(number, number // divisor, divisor))
                        break
                    divisor += 2
                if divisor == (number // 2) + 1:
                    print("{}={}*{}".format(number, number, 1))
    except IndexError:
        pass

factorization()
